language: node_js
node_js:
- '8'
dist: trusty
before_install: |
  set -e
  date
install: |
  set -e
  date
script: npm run test 2>&1
after_failure: tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
deploy:
  - provider: script
    script: "./.travis/stable.sh ${TRAVIS_TAG}"
    skip_cleanup: true
    on:
      branch: master
      tags: true
      repo: accordproject/jura-compiler
cache:
  directories:
  - node_modules
services: 
