language: node_js
node_js:
- '8'
dist: trusty
before_install: |
  set -e
  export PATH="./$HOME/node_modules/.bin:$PATH"
  date
install: |
  set -e
  date
  npm install
  date
script: npm run test 2>&1
after_failure: tail -n +1 -- /home/travis/.npm/_logs/*-debug.log
cache:
  directories:
  - node_modules
services: 
